POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer USER_LOGIN_TOKEN

{
    "title": "test blog 1",
    "author": "test author 1",
    "url": "testURL_1",
    "likes": 1
}